### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMOTY: out of memory

### ISSUE THREAD

**Issue by jaehwlee** [hn826/distributed-tensorflow#1]
![image](https://user-images.githubusercontent.com/33409264/105456767-14147900-5cc9-11eb-83fa-80da4f4cc523.png)

I got an memory error when I tried to execute the code in local.
How can I fixt the error?

**Comment by jaehwlee** [comment]
I solved this problem by assigning task for each GPU.
But I have to use only one worker to execute the code without memory error. Because I have only 2 GPUs in local.
I made server.py and worker.py, and then add the line following :
<pre>
<code>
# server.py, main
os.environ["CUDA_VISIBLE_DEVICES"]="0"

#worker.py, main
os.environ["CUDA_VISIBLE_DEVICES"]="1"
</code>
</pre>
